apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: registry/namespace/hello-world:1
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: secret